### ISSUE TITLE
Displaying rankings with 5 qualifier rounds

### ISSUE THREAD

**Issue by Azathoth2k** [rtfoley/fllipit#8]
More of a request than an issue.  How difficult would it be to modify the display so that the rankings are based on the results of 5 qualification rounds instead of 3.  The underlying MS Access App/DB have been modified to support 5 qualification rounds.

Thx

**Comment by rtfoley** [comment]
I'll get the latest DB and take a look.

**Comment by Azathoth2k** [comment]
I made a run at it and I think I have it working but if you could take a look that would be great.
Thanks,
Keith


-----Original Message-----

**Comment by rtfoley** [comment]
This should be all set now

**Comment by Azathoth2k** [comment]
I ran a quick test and it looks good.  I will do more extensive testing at our meeting on Tuesday.
Thanks,
Keith


-----Original Message-----
